require 'rails_helper'

RSpec.describe ReturnRequest, type: :model do
  describe 'associations' do
    it { should belong_to(:user) }
    it { should belong_to(:order) }
    it { should have_many(:return_items).dependent(:destroy) }
  end

  describe 'factory' do
    it 'has a valid factory' do
      return_request = build(:return_request)
      expect(return_request).to be_valid
    end
  end

  # Enum methods are automatically generated by Rails
end