# frozen_string_literal: true

class SeedNavigationItems < ActiveRecord::Migration[7.1]
  def up
    navigation_items = [
      {
        key: 'dashboard',
        label: 'Dashboard',
        icon: 'fas fa-tachometer-alt',
        path_method: 'admin_dashboard_path',
        section: nil,
        required_permissions: ['dashboard:view'].to_json,
        always_visible: true,
        can_view: true,
        can_create: false,
        can_edit: false,
        can_delete: false,
        view_permissions: ['dashboard:view'].to_json,
        display_order: 0,
        is_system: true,
        controller_name: 'dashboard',
        description: 'Main dashboard overview'
      },
      {
        key: 'users',
        label: 'Customers',
        icon: 'fas fa-users',
        path_method: 'admin_users_path',
        section: 'User Management',
        required_permissions: ['users:view', 'customers:view', 'users:read'].to_json,
        can_view: true,
        can_create: false,
        can_edit: true,
        can_delete: true,
        view_permissions: ['users:view', 'customers:view'].to_json,
        create_permissions: ['users:create'].to_json,
        edit_permissions: ['users:update', 'users:edit'].to_json,
        delete_permissions: ['users:delete', 'users:destroy'].to_json,
        display_order: 0,
        is_system: true,
        controller_name: 'users',
        description: 'Manage customer accounts'
      },
      {
        key: 'suppliers',
        label: 'Suppliers',
        icon: 'fas fa-store',
        path_method: 'admin_suppliers_path',
        section: 'User Management',
        required_permissions: ['suppliers:view', 'suppliers:read'].to_json,
        can_view: true,
        can_create: true,
        can_edit: true,
        can_delete: true,
        view_permissions: ['suppliers:view'].to_json,
        create_permissions: ['suppliers:create'].to_json,
        edit_permissions: ['suppliers:update', 'suppliers:edit'].to_json,
        delete_permissions: ['suppliers:delete', 'suppliers:destroy'].to_json,
        display_order: 1,
        is_system: true,
        controller_name: 'suppliers',
        description: 'Manage supplier accounts'
      },
      {
        key: 'admins',
        label: 'Admins',
        icon: 'fas fa-user-shield',
        path_method: 'admin_admins_path',
        section: 'User Management',
        required_permissions: ['admins:view', 'admins:read'].to_json,
        require_super_admin: true,
        can_view: true,
        can_create: true,
        can_edit: true,
        can_delete: true,
        view_permissions: ['admins:view'].to_json,
        create_permissions: ['admins:create'].to_json,
        edit_permissions: ['admins:update', 'admins:edit'].to_json,
        delete_permissions: ['admins:delete', 'admins:destroy'].to_json,
        display_order: 2,
        is_system: true,
        controller_name: 'admins',
        description: 'Manage admin accounts'
      },
      {
        key: 'products',
        label: 'Products',
        icon: 'fas fa-box',
        path_method: 'admin_products_path',
        section: 'Product Management',
        required_permissions: ['products:view', 'products:read'].to_json,
        can_view: true,
        can_create: true,
        can_edit: true,
        can_delete: true,
        view_permissions: ['products:view'].to_json,
        create_permissions: ['products:create'].to_json,
        edit_permissions: ['products:update', 'products:edit'].to_json,
        delete_permissions: ['products:delete', 'products:destroy'].to_json,
        display_order: 0,
        is_system: true,
        controller_name: 'products',
        description: 'Manage products and catalog'
      },
      {
        key: 'categories',
        label: 'Categories',
        icon: 'fas fa-tags',
        path_method: 'admin_categories_path',
        section: 'Product Management',
        required_permissions: ['categories:view', 'categories:read', 'products:view'].to_json,
        can_view: true,
        can_create: true,
        can_edit: true,
        can_delete: true,
        view_permissions: ['categories:view'].to_json,
        create_permissions: ['categories:create'].to_json,
        edit_permissions: ['categories:update', 'categories:edit'].to_json,
        delete_permissions: ['categories:delete', 'categories:destroy'].to_json,
        display_order: 1,
        is_system: true,
        controller_name: 'categories',
        description: 'Manage product categories'
      },
      {
        key: 'orders',
        label: 'Orders',
        icon: 'fas fa-shopping-cart',
        path_method: 'admin_orders_path',
        section: 'Orders',
        required_permissions: ['orders:view', 'orders:read'].to_json,
        can_view: true,
        can_create: false,
        can_edit: true,
        can_delete: false,
        view_permissions: ['orders:view'].to_json,
        edit_permissions: ['orders:update', 'orders:edit'].to_json,
        display_order: 0,
        is_system: true,
        controller_name: 'orders',
        description: 'Manage orders and fulfillment'
      },
      {
        key: 'promotions',
        label: 'Promotions',
        icon: 'fas fa-bullhorn',
        path_method: 'admin_promotions_path',
        section: 'Marketing',
        required_permissions: ['promotions:view', 'promotions:read', 'marketing:view'].to_json,
        can_view: true,
        can_create: true,
        can_edit: true,
        can_delete: true,
        view_permissions: ['promotions:view'].to_json,
        create_permissions: ['promotions:create'].to_json,
        edit_permissions: ['promotions:update', 'promotions:edit'].to_json,
        delete_permissions: ['promotions:delete', 'promotions:destroy'].to_json,
        display_order: 0,
        is_system: true,
        controller_name: 'promotions',
        description: 'Manage promotions and campaigns'
      },
      {
        key: 'coupons',
        label: 'Coupons',
        icon: 'fas fa-ticket-alt',
        path_method: 'admin_coupons_path',
        section: 'Marketing',
        required_permissions: ['coupons:view', 'coupons:read', 'marketing:view'].to_json,
        can_view: true,
        can_create: true,
        can_edit: true,
        can_delete: true,
        view_permissions: ['coupons:view'].to_json,
        create_permissions: ['coupons:create'].to_json,
        edit_permissions: ['coupons:update', 'coupons:edit'].to_json,
        delete_permissions: ['coupons:delete', 'coupons:destroy'].to_json,
        display_order: 1,
        is_system: true,
        controller_name: 'coupons',
        description: 'Manage discount coupons'
      },
      {
        key: 'reports',
        label: 'Reports',
        icon: 'fas fa-chart-bar',
        path_method: 'admin_reports_path',
        section: 'Reports',
        required_permissions: ['reports:view', 'reports:read', 'analytics:view'].to_json,
        can_view: true,
        can_create: false,
        can_edit: false,
        can_delete: false,
        view_permissions: ['reports:view', 'analytics:view'].to_json,
        display_order: 0,
        is_system: true,
        controller_name: 'reports',
        description: 'View reports and analytics'
      },
      {
        key: 'audit_logs',
        label: 'Activity History',
        icon: 'fas fa-history',
        path_method: 'admin_audit_logs_path',
        section: 'System',
        required_permissions: ['audit_logs:view', 'audit_logs:read'].to_json,
        require_super_admin: true,
        can_view: true,
        can_create: false,
        can_edit: false,
        can_delete: false,
        view_permissions: ['audit_logs:view'].to_json,
        display_order: 0,
        is_system: true,
        controller_name: 'audit_logs',
        description: 'View system activity history'
      },
      {
        key: 'settings',
        label: 'Settings',
        icon: 'fas fa-cog',
        path_method: 'admin_settings_path',
        section: 'System',
        required_permissions: ['settings:view', 'settings:read'].to_json,
        require_super_admin: true,
        can_view: true,
        can_create: false,
        can_edit: true,
        can_delete: false,
        view_permissions: ['settings:view'].to_json,
        edit_permissions: ['settings:update', 'settings:edit'].to_json,
        display_order: 1,
        is_system: true,
        controller_name: 'settings',
        description: 'System settings and configuration'
      },
      {
        key: 'email_templates',
        label: 'Email Templates',
        icon: 'fas fa-envelope',
        path_method: 'admin_email_templates_path',
        section: 'System',
        required_permissions: ['email_templates:view', 'email_templates:read'].to_json,
        require_super_admin: true,
        can_view: true,
        can_create: true,
        can_edit: true,
        can_delete: true,
        view_permissions: ['email_templates:view'].to_json,
        create_permissions: ['email_templates:create'].to_json,
        edit_permissions: ['email_templates:update', 'email_templates:edit'].to_json,
        delete_permissions: ['email_templates:delete', 'email_templates:destroy'].to_json,
        display_order: 2,
        is_system: true,
        controller_name: 'email_templates',
        description: 'Manage email templates'
      },
      {
        key: 'system_configurations',
        label: 'System Configurations',
        icon: 'fas fa-sliders-h',
        path_method: 'admin_system_configurations_path',
        section: 'System',
        required_permissions: ['system_configurations:view', 'system_configurations:read'].to_json,
        require_super_admin: false, # All admins can access, but filtered by role in controller
        can_view: true,
        can_create: true,
        can_edit: true,
        can_delete: true,
        view_permissions: ['system_configurations:view'].to_json,
        create_permissions: ['system_configurations:create'].to_json,
        edit_permissions: ['system_configurations:update', 'system_configurations:edit'].to_json,
        delete_permissions: ['system_configurations:delete', 'system_configurations:destroy'].to_json,
        display_order: 3,
        is_system: true,
        controller_name: 'system_configurations',
        description: 'Manage system configurations (key-value pairs)'
      },
      {
        key: 'roles_permissions',
        label: 'Roles & Permissions',
        icon: 'fas fa-user-lock',
        path_method: 'admin_rbac_roles_path',
        section: 'System',
        required_permissions: ['rbac:view', 'rbac:read'].to_json,
        require_super_admin: true,
        can_view: true,
        can_create: false,
        can_edit: true,
        can_delete: false,
        view_permissions: ['rbac:view'].to_json,
        edit_permissions: ['rbac:update', 'rbac:edit'].to_json,
        display_order: 4,
        is_system: true,
        controller_name: 'rbac_roles',
        description: 'Manage roles and their permissions. View what permissions each role has.'
      },
      {
        key: 'navigation_items',
        label: 'Navigation Items',
        icon: 'fas fa-bars',
        path_method: 'admin_navigation_items_path',
        section: 'System',
        required_permissions: ['navigation_items:view', 'navigation_items:read'].to_json,
        require_super_admin: true,
        can_view: true,
        can_create: true,
        can_edit: true,
        can_delete: true,
        view_permissions: ['navigation_items:view'].to_json,
        create_permissions: ['navigation_items:create'].to_json,
        edit_permissions: ['navigation_items:update', 'navigation_items:edit'].to_json,
        delete_permissions: ['navigation_items:delete', 'navigation_items:destroy'].to_json,
        display_order: 5,
        is_system: true,
        controller_name: 'navigation_items',
        description: 'Manage navigation menu items and permissions'
      }
    ]
    
    # Only seed if table exists (for fresh installs)
    if ActiveRecord::Base.connection.table_exists?('navigation_items')
      navigation_items.each do |item_data|
        item = NavigationItem.find_or_initialize_by(key: item_data[:key])
        item.assign_attributes(item_data)
        item.is_system = true # Ensure system items are marked
        item.is_active = true unless item_data.key?(:is_active)
        item.save!
      end
    end
  end
  
  def down
    if ActiveRecord::Base.connection.table_exists?('navigation_items')
      NavigationItem.where(is_system: true).destroy_all
    end
  end
end

